# ------------------------------------------------------------
# Global K3s configuration
# ------------------------------------------------------------
k3s_version: "v1.34.3+k3s1"

timezone: America/Mexico_City