# inventories/N70/group_vars/k3s_control_plane.yml

# ------------------------------------------------------------
# Node configuration
# ------------------------------------------------------------
k3s_node_name: "k3s-cp-1"

# ------------------------------------------------------------
# Disable default components
# ------------------------------------------------------------
k3s_disable_components:
  - traefik

# ------------------------------------------------------------
# K3s server extra arguments
# ------------------------------------------------------------
k3s_extra_args: []
