# inventories/N70/group_vars/k3s_control_plane.yml

# ------------------------------------------------------------
# K3s version
# https://docs.k3s.io/release-notes/v1.34.X#release-v1341k3s1
# ------------------------------------------------------------
k3s_version: "v1.34.3+k3s1"

# ------------------------------------------------------------
# Node configuration
# ------------------------------------------------------------
k3s_node_name: "k3s-cp-1"

# ------------------------------------------------------------
# Disable default components
# ------------------------------------------------------------
k3s_disable_components:
  - traefik

# ------------------------------------------------------------
# K3s server extra arguments
# ------------------------------------------------------------
k3s_extra_args: []
