# inventories/N70/group_vars/k3s_agents.yml

# ------------------------------------------------------------
# K3s server endpoint
# ------------------------------------------------------------
k3s_server_url: "https://192.168.122.29:6443"

# ------------------------------------------------------------
# Control plane inventory hostname
# ------------------------------------------------------------
k3s_control_plane_host: "k3s-cp-1"

# ------------------------------------------------------------
# Extra agent arguments (optional)
# ------------------------------------------------------------
k3s_agent_extra_args: []
