# ------------------------------------------------------------
# Node configuration
# ------------------------------------------------------------
k3s_node_name: "k3s-cp-1"

# ------------------------------------------------------------
# Disable default components
# ------------------------------------------------------------
k3s_disable_components:
  - traefik

# ------------------------------------------------------------
# K3s server networking (API exposure via Tailscale)
# ------------------------------------------------------------
k3s_advertise_address: "xx.xx.xx.xx"
k3s_bind_address: "0.0.0.0"

k3s_tls_sans:
  - "xx.xx.xx.xx"

# ------------------------------------------------------------
# K3s server extra arguments
# ------------------------------------------------------------
k3s_extra_args: []
